server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:

        - id: employee-service
          uri: lb://employee-app
          predicates:
            - Path=/employee-app/api/v2/employees/**
          filters:
            - AuthenticationFilter



        - id: address-service
          uri: lb://address-app
          predicates:
            - Path=/address-app/api/v1/address/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**