server:
  port: 8081
  servlet:
    context-path: /address-app/api

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    password: password
    username: root
    url: jdbc:mysql://127.0.0.1:3306/address
  application:
    name: address-app

  #our address service should connect to our service registry of:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/