server:
  port: 8082
  servlet:
    context-path: /employee-app/api
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    password: password
    username: root
    url: jdbc:mysql://127.0.0.1:3306/employee
  application:
    name: employee-app
